version: "3.9"
services:
  postgres:
    platform: linux/amd64
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d postgres && sleep 5
      interval: 1s
      retries: 30
    ports:
      - "5432:5432"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
